name: Rust Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: mdbook-bibfile-referencing

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
        uses: KyleMayes/install-llvm-action@32c4866ebb71e0949e8833eb49beeebed48532bd
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Cargo Test
        run: cargo test -- --nocapture
        working-directory: ./rust-bindings

      - name: no_std
        run: cargo build --no-default-features
        working-directory: ./rust-bindings


  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cargo Format Check
        run: cargo fmt -- --check
        working-directory: ./rust-bindings

      - name: Cargo Sort Check
        run: cargo install cargo-sort && cargo-sort --check
        working-directory: ./rust-bindings
