name: Rust Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Cargo Test
        run: cargo test -- --nocapture
        working-directory: ./rust

      - name: Cargo Clippy Check
        run: cargo clippy --all-features --workspace -- -D warnings
        working-directory: ./rust

  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cargo Format Check
        run: cargo fmt -- --check
        working-directory: ./rust

      - name: Cargo Sort Check
        run: cargo install cargo-sort && cargo-sort --check
        working-directory: ./rust
